28/11/2018 03:21:36 PM ...Stage all, before: Error!
msg.:(MaxRetryError("HTTPConnectionPool(host='proxylatam.indra.es', port=8080): Max retries exceeded with url: http://chromedriver.storage.googleapis.com/LATEST_RELEASE (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0A004250>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)))",),)
28/11/2018 03:21:36 PM ...Stage all, after: Error!
msg.:("'Context' object has no attribute 'app'",)
